"""Feedback persistence and continuous self-learning pipeline for the FAQ chatbot.

Saves structured user feedback (👍 / 👎) to persistent storage and dynamically
augments Qdrant with learned query phrasing variants upon positive verification.
"""

from datetime import datetime, timezone
import json
from pathlib import Path
import threading
from typing import Any, Dict, List, Optional

from config.settings import settings
from src.utils.logger import logger
from src.vectorstore.qdrant_client import QdrantManager, get_embedding_function

_LOCK = threading.Lock()


def _ensure_storage_dir(file_path: str) -> Path:
    """Ensures parent directory for feedback log exists and returns Path object."""
    path = Path(file_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def learn_variant_into_qdrant(
    user_query: str,
    top_source: Dict[str, Any],
) -> bool:
    """Embeds user phrasing and indexes it as a new learned variant vector in Qdrant.

    Args:
        user_query: The customer's real question phrasing.
        top_source: Metadata dict of the FAQ document that successfully answered the query.

    Returns:
        True if successfully indexed, False otherwise.
    """
    clean_query = user_query.strip()
    if len(clean_query) < 5:
        return False

    faq_question = top_source.get("question", "")
    # If the user query is already identical to canonical FAQ question, skip
    if clean_query.lower() == faq_question.strip().lower():
        logger.debug("User query matches canonical question exactly; skipping variant ingestion.")
        return False

    try:
        embedder = get_embedding_function(task_type="retrieval_document")
        query_vector = embedder.embed_query(clean_query)

        qdrant = QdrantManager(
            storage_path=settings.qdrant_storage_path,
            collection_name=settings.qdrant_collection_name,
        )

        metadata = {
            "id": top_source.get("id", "FAQ"),
            "category": top_source.get("category", "Umum"),
            "question": faq_question,
            "answer": top_source.get("answer", ""),
            "learned_at": datetime.now(timezone.utc).isoformat(),
        }

        return qdrant.upsert_learned_variant(
            query_text=clean_query,
            embedding=query_vector,
            metadata=metadata,
        )

    except Exception as e:
        logger.error(f"Failed to learn variant '{clean_query}' into Qdrant: {e}")
        return False


def record_user_feedback(
    session_id: str,
    message_index: int,
    user_query: str,
    assistant_response: str,
    rating: str,
    sources: Optional[List[Dict[str, Any]]] = None,
    elapsed_seconds: Optional[float] = None,
) -> Dict[str, Any]:
    """Records user feedback to JSONL and triggers autonomous self-learning on positive feedback.

    Args:
        session_id: Unique thread conversation ID.
        message_index: Index of the message in the conversation.
        user_query: The question text from the user.
        assistant_response: The answer generated by the assistant.
        rating: 'up' (👍) or 'down' (👎).
        sources: FAQ attribution list containing referenced FAQ documents.
        elapsed_seconds: Latency duration of response generation.

    Returns:
        The serialized feedback record dictionary.
    """
    sources_list = sources or []
    rating_clean = rating.lower().strip()
    is_upvote = rating_clean in {"up", "good", "positive", "1"}
    is_learned = False

    # Autonomous Self-Learning: If rated 👍 and backed by valid FAQ source, index variant into Qdrant
    if is_upvote and settings.enable_self_learning and user_query and sources_list:
        top_source = sources_list[0]
        if top_source and top_source.get("id"):
            is_learned = learn_variant_into_qdrant(
                user_query=user_query,
                top_source=top_source,
            )

    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "session_id": session_id,
        "message_index": message_index,
        "user_query": user_query,
        "assistant_response": assistant_response,
        "rating": "up" if is_upvote else "down",
        "sources": sources_list,
        "elapsed_seconds": elapsed_seconds,
        "learned_as_variant": is_learned,
    }

    log_path = _ensure_storage_dir(settings.feedback_storage_path)

    with _LOCK:
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
            logger.info(
                f"Feedback recorded: {record['rating'].upper()} for session {session_id[:8]} (Learned: {is_learned})"
            )
        except Exception as e:
            logger.error(f"Failed to append feedback record to {log_path}: {e}")

    return record


def get_feedback_analytics() -> Dict[str, Any]:
    """Computes summary statistics from the persistent feedback store."""
    log_path = Path(settings.feedback_storage_path)
    if not log_path.exists():
        return {
            "total_feedbacks": 0,
            "upvotes": 0,
            "downvotes": 0,
            "satisfaction_rate": 100.0,
            "learned_variants": 0,
        }

    total = 0
    upvotes = 0
    downvotes = 0
    learned = 0

    with _LOCK:
        try:
            with open(log_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    data = json.loads(line)
                    total += 1
                    if data.get("rating") == "up":
                        upvotes += 1
                    else:
                        downvotes += 1
                    if data.get("learned_as_variant"):
                        learned += 1
        except Exception as e:
            logger.error(f"Failed to read feedback analytics: {e}")

    satisfaction = (upvotes / total * 100.0) if total > 0 else 100.0

    return {
        "total_feedbacks": total,
        "upvotes": upvotes,
        "downvotes": downvotes,
        "satisfaction_rate": round(satisfaction, 1),
        "learned_variants": learned,
    }


def get_recent_feedbacks(limit: int = 50) -> List[Dict[str, Any]]:
    """Retrieves the most recent feedback entries."""
    log_path = Path(settings.feedback_storage_path)
    if not log_path.exists():
        return []

    records: List[Dict[str, Any]] = []
    with _LOCK:
        try:
            with open(log_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        records.append(json.loads(line))
        except Exception as e:
            logger.error(f"Failed to read recent feedbacks: {e}")

    return records[-limit:]


def get_unresolved_queries() -> List[Dict[str, Any]]:
    """Retrieves queries flagged with negative feedback for FAQ gap analysis."""
    all_records = get_recent_feedbacks(limit=500)
    return [r for r in all_records if r.get("rating") == "down"]
